services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis-data:/data
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - redis
volumes:
  redis-data:
    driver: local